Exclude org.scannotation again; move temp files to temp dir; avoid resolving deps twice

diff --git a/zanataj b/zanataj
--- a/zanataj
+++ b/zanataj
@@ -2,9 +2,6 @@
 
 : ${ZANATA_CLI_VERSION:="2.0.2-SNAPSHOT"}
 
-# From http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in
-ZANATAJ_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
-
 IVY_JAR=/usr/share/java/ivy.jar
 if [ ! -r $IVY_JAR ]; then
   echo "Please install Apache Ivy to $IVY_JAR."
@@ -16,17 +13,14 @@ fi
 # Documentation for Ivy's command-line options are here:
 # http://ant.apache.org/ivy/history/latest-milestone/standalone.html
 # http://ant.apache.org/ivy/history/2.1.0/standalone.html
+# java -jar /usr/share/java/ivy.jar -?
 
-unset IVY_LOG_LEVEL IVY_REFRESH IVY_SETTINGS
+WORKDIR=$(mktemp --directory)
 
-# -error will omit ivy warnings
-IVY_LOG_LEVEL=-error
-
-# -refresh tells ivy to 'refresh dynamic resolved revisions' (eg SNAPSHOT deps)
-IVY_REFRESH=-refresh
+IVYSETTINGS_XML="$WORKDIR/ivysettings.xml"
 
 # ivysettings.xml as a here document
-cat > $ZANATAJ_HOME/zanataj-ivysettings.xml <<EOF
+cat > $IVYSETTINGS_XML <<EOF
 <ivysettings>
     <settings defaultResolver="default"/>
     <property name="repoPath" value="\${user.home}/.m2/repository" />
@@ -52,9 +46,26 @@ cat > $ZANATAJ_HOME/zanataj-ivysettings.xml <<EOF
 EOF
 
 # override ivy resolvers
-IVY_SETTINGS="-settings $ZANATAJ_HOME/zanataj-ivysettings.xml"
+IVY_SETTINGS="-settings $IVYSETTINGS_XML"
 
-IVY_LOG=$(mktemp)
+IVY_XML="$WORKDIR/ivy.xml"
+
+# ivy.xml as a here document
+cat > $IVY_XML <<EOF
+<ivy-module version="2.0">
+    <info organisation="org.zanata" module="zanataj" />
+    <dependencies>
+        <dependency org="org.zanata" name="zanata-cli" rev="$ZANATA_CLI_VERSION">
+            <!-- Omit unneeded dependency which conflicts with another one -->
+            <exclude org="org.scannotation" />
+        </dependency>
+    </dependencies>
+</ivy-module>
+EOF
+
+IVY_CONFIG="-ivy $IVY_XML"
+
+IVY_LOG=$WORKDIR/ivy.log
 
 # Other java options
 JAVA_OPTS=""
@@ -64,28 +75,22 @@ JAVA_OPTS=""
 # Resolve dependencies with ivy's normal logging
 # but only output to console in case of failure.
 
+# -refresh tells ivy to 'refresh dynamic resolved revisions' (eg SNAPSHOT deps)
+
+echo "Resolving dependencies..."
 java \
   -jar $IVY_JAR \
-  -dependency org.zanata zanata-cli $ZANATA_CLI_VERSION \
-  $IVY_REFRESH $IVY_SETTINGS > $IVY_LOG ||
-  (cat $IVY_LOG; rm -f $IVY_LOG; exit 1)
+  -refresh \
+  -cachepath $WORKDIR/classpath \
+  $IVY_CONFIG $IVY_SETTINGS > $IVY_LOG ||
+  (echo "ERROR: dependency resolution failed.  Ivy log follows:"; cat $IVY_LOG; rm -f $IVY_LOG; exit 1)
 rm -f $IVY_LOG
 
-LOGGING_OPTS="
-  -Dorg.slf4j.simpleLogger.showDateTime=false
-  -Dorg.slf4j.simpleLogger.showThreadName=false
-  -Dorg.slf4j.simpleLogger.showLogName=false
-  -Dorg.slf4j.simpleLogger.showShortLogName=false
-  -Dorg.slf4j.simpleLogger.levelInBrackets=true
-"
+# Invoke ZanataClient
 
-# Invoke ZanataClient (and Ivy again) with minimal ivy logging (no ivy refresh)
+java $JAVA_OPTS \
+  -cp $(cat $WORKDIR/classpath) \
+  org.zanata.client.ZanataClient "$@"
 
-java \
-  $JAVA_OPTS \
-  $LOGGING_OPTS \
-  -jar $IVY_JAR \
-  -dependency org.zanata zanata-cli $ZANATA_CLI_VERSION \
-  $IVY_LOG_LEVEL $IVY_SETTINGS \
-  -main org.zanata.client.ZanataClient -args -- \
-  "$@"
+# clean up ivy.xml ivysettings.xml ivy.log
+#rm -fr $WORKDIR
